# Generated by Django 3.2.14 on 2022-08-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='stduent',
            new_name='student',
        ),
    ]
