# Generated by Django 3.2.14 on 2022-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_word_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.BooleanField(default=False),
        ),
    ]
