# Generated by Django 3.2.14 on 2022-08-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='fail_words',
            field=models.ManyToManyField(blank=True, null=True, related_name='fail_word', to='word.Word'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_words',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_word', to='word.Word'),
        ),
    ]
