# Generated by Django 3.2.14 on 2022-08-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail_words', models.ManyToManyField(blank=True, null=True, related_name='word_fail', to='word.Word')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_std', to='word.student')),
            ],
        ),
    ]
