# Generated by Django 3.2.14 on 2022-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_auto_20221123_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_kor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
