# Generated by Django 3.2.14 on 2022-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_word_word_kor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_kor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
