# Generated by Django 3.2.14 on 2023-01-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0011_alter_test_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='std_test', to='word.student'),
        ),
    ]
