from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^search/$',
        view=views.Search.as_view(),
        name='studentSearch'
    ),
    url(
        regex=r'^info/$',
        view=views.StudentInfo.as_view(),
        name='studentInfo'
    ),
    url(
        regex=r'^register/$',
        view=views.StudentRegister.as_view(),
        name='studentRegister'
    ),
    url(
        regex=r'^maketest/$',
        view=views.Maketest.as_view(),
        name='makeTest'
    ),
    url(
        regex=r'^test/$',
        view=views.TestInfo.as_view(),
        name='test'
    ),
    url(
        regex=r'^getstdtest/$',
        view=views.getStudentTest.as_view(),
        name='test'
    ),
    url(
        regex=r'^setfail/$',
        view=views.setTestFail.as_view(),
        name='test'
    ),
    url(
        regex=r'^class/$',
        view=views.getClass.as_view(),
        name='test'
    ),
    url(
        regex=r'^classperson/$',
        view=views.getClassPerson.as_view(),
        name='test'
    ),
    url(
        regex=r'^setpersonbigo/$',
        view=views.setStudentBigo.as_view(),
        name='test'
    ),
    url(
        regex=r'^delete/$',
        view=views.deletebook.as_view(),
        name='test'
    ),
    url(
        regex=r'^deletetest/$',
        view=views.deleteTest.as_view(),
        name='test'
    ),
    url(
        regex=r'^bookname/$',
        view=views.getBook_name.as_view(),
        name='test'
    ),
    url(
        regex=r'^makeexcelandimg/$',
        view=views.makeExcelAndImg.as_view(),
        name='test'
    ),
    url(
        regex=r'^failWordRegister/$',
        view=views.failWordRegister.as_view(),
        name='test'
    )
]